modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="taysrandomthings"
version="1.0.0"
displayName="Tays Random Things"
displayURL="https://github.com/Taygamer/Tay-s-Random-Things"
credits="Made by Taygamerlol"
authors="Taygamerlol"
description="Adds Random things i thought was funny"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.taysrandomthings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration